import type { OverlaySpec } from "../overlay-resolver";
import type { SentenceDef } from "../tts-pipeline";
import type { ImageQuery } from "../image-pipeline";

export const TOPIC = "How the Federal Reserve Controls Your Money";
export const SLUG = "how-the-fed-controls-your-money";

export const SENTENCES: SentenceDef[] = [
  { text: "Every dollar you've ever spent has been shaped by twelve people.", emphasis: ["Every", "dollar"], palette: "warm-real" },
  { text: "They meet eight times a year.", emphasis: ["meet", "times"], palette: "cool-tech" },
  { text: "And in two hours, they can raise your mortgage by $500 a month.", emphasis: ["mortgage", "$500"], palette: "warm-real" },
  { text: "This is the Federal Reserve.", emphasis: ["Federal", "Reserve"], palette: "cool-tech" },
  { text: "The Fed's main lever is the federal funds rate.", emphasis: ["lever", "rate"], palette: "cool-tech" },
  { text: "It's the price banks pay to borrow money overnight.", emphasis: ["Banks", "pay", "borrow"], palette: "cool-tech" },
  { text: "When that rate goes up, every loan in America gets more expensive.", emphasis: ["rate", "up", "expensive"], palette: "warm-real" },
  { text: "In 2022, inflation hit 9.1 percent — the highest in 40 years.", emphasis: ["2022", "inflation", "9.1"], palette: "cool-tech" },
  { text: "The Fed's response was aggressive.", emphasis: ["Fed's", "response", "aggressive"], palette: "cool-tech" },
  { text: "Seven rate hikes in twelve months.", emphasis: ["Seven", "rate", "hikes"], palette: "cool-tech" },
  { text: "Mortgage rates went from 3 percent to over 7 percent.", emphasis: ["3", "7"], palette: "warm-real" },
  { text: "Monthly payments on a median home jumped by $800.", emphasis: ["jumped"], palette: "warm-real" },
  { text: "Millions of buyers were priced out overnight.", emphasis: ["Millions", "priced", "out"], palette: "warm-real" },
  { text: "That was the transmission mechanism working exactly as intended.", emphasis: ["transmission", "mechanism"], palette: "cool-tech" },
  { text: "High rates slow spending, cool prices, and reduce growth.", emphasis: ["High", "rates", "cool"], palette: "cool-tech" },
  { text: "But they also freeze the housing market and crush startup funding.", emphasis: ["freeze", "housing", "market", "startup"], palette: "warm-real" },
  { text: "Today, the Fed holds $7.4 trillion in assets.", emphasis: ["Fed", "holds", "$7.4"], palette: "cool-tech" },
  { text: "More than the GDP of every country except the US and China.", emphasis: ["More", "GDP", "China"], palette: "cool-tech" },
  { text: "Understanding the Fed isn't academic.", emphasis: ["Understanding", "Fed", "isn't"], palette: "warm-real" },
  { text: "It's the operating manual for your financial life.", emphasis: ["operating", "manual", "financial"], palette: "warm-real" },
];

export const OVERLAY_SPECS: OverlaySpec[] = [
  {
    type: "kinetic-number",
    text: "FEDERAL FUNDS RATE",
    value: 5.25,
    unit: "%",
    palette: "cool-tech",
    anchorPhrase: "federal funds rate",
    holdSec: 3.0,
  },
  {
    type: "headline-card",
    text: "INFLATION: 9.1%",
    source: "CPI, June 2022 — 40-year high",
    palette: "cool-tech",
    anchorPhrase: "inflation",
    holdSec: 3.5,
  },
  {
    type: "kinetic-number",
    text: "MONTHLY PAYMENT INCREASE",
    value: 800,
    unit: "$",
    palette: "warm-real",
    anchorPhrase: "$800",
    holdSec: 3.0,
  },
  {
    type: "headline-card",
    text: "FED BALANCE SHEET: $7.4 TRILLION",
    source: "Federal Reserve H.4.1, May 2024",
    palette: "cool-tech",
    anchorPhrase: "7.4",
    holdSec: 4.0,
  },
];

export const IMAGE_QUERIES: ImageQuery[] = [
  { slot: 0, query: "federal reserve building washington dc exterior", fallback: "government building architecture" },
  { slot: 1, query: "board of directors meeting suits formal", fallback: "business meeting conference room" },
  { slot: 2, query: "dollar bills close up macro currency", fallback: "american currency money" },
  { slot: 3, query: "government institution capitol building", fallback: "official government building" },
  { slot: 4, query: "policy makers podium press conference", fallback: "formal press conference podium" },
  { slot: 5, query: "american currency dollar bills stack", fallback: "cash money dollars" },
  { slot: 6, query: "financial institution exterior modern building", fallback: "office building exterior" },
  { slot: 7, query: "economists office desk papers macro", fallback: "office desk professional" },
  { slot: 8, query: "monetary policy chart graph screen", fallback: "financial chart graph screen" },
  { slot: 9, query: "central bank logo signage building", fallback: "bank exterior signage" },
  { slot: 10, query: "interest rate arrow rising chart graph", fallback: "financial chart upward trend" },
  { slot: 11, query: "bank loan documents papers signing", fallback: "loan application documents" },
  { slot: 12, query: "overnight lending finance banking concept", fallback: "banking finance concept" },
  { slot: 13, query: "credit card payment transaction close up", fallback: "credit card finance" },
  { slot: 14, query: "bank vault door security steel", fallback: "secure bank vault" },
  { slot: 15, query: "lending rates newspaper headline finance", fallback: "newspaper finance section" },
  { slot: 16, query: "financial data screen monitor trading", fallback: "stock market screen data" },
  { slot: 17, query: "banker office professional desk", fallback: "professional office desk" },
  { slot: 18, query: "loan application papers form closeup", fallback: "documents paperwork desk" },
  { slot: 19, query: "bank teller window counter service", fallback: "bank interior counter" },
  { slot: 20, query: "grocery store price tags aisle", fallback: "supermarket grocery aisle" },
  { slot: 21, query: "inflation receipt cashier groceries", fallback: "grocery store checkout" },
  { slot: 22, query: "rising prices supermarket food aisle", fallback: "grocery store food display" },
  { slot: 23, query: "CPI chart graph inflation data", fallback: "economic chart graph rising" },
  { slot: 24, query: "gas station price sign fuel", fallback: "petrol station fuel prices" },
  { slot: 25, query: "consumer price index economy concept", fallback: "economy inflation concept" },
  { slot: 26, query: "empty shelves store shortage supply", fallback: "empty retail shelves" },
  { slot: 27, query: "paycheck budget squeeze personal finance", fallback: "personal finance budget" },
  { slot: 28, query: "cost of living urban city expensive", fallback: "expensive city urban living" },
  { slot: 29, query: "inflation graph newspaper headline economy", fallback: "economic newspaper headline" },
  { slot: 30, query: "real estate for sale sign front yard", fallback: "house for sale sign" },
  { slot: 31, query: "housing market graph decline chart", fallback: "real estate chart downward" },
  { slot: 32, query: "mortgage documents signing couple home", fallback: "home loan signing documents" },
  { slot: 33, query: "couple house hunting real estate agent", fallback: "couple looking at house" },
  { slot: 34, query: "foreclosure sign neighborhood house", fallback: "foreclosed home exterior" },
  { slot: 35, query: "empty open house living room", fallback: "empty living room interior" },
  { slot: 36, query: "first time buyer keys new home", fallback: "new home keys house" },
  { slot: 37, query: "house price chart growth graph", fallback: "property price chart" },
  { slot: 38, query: "real estate agent showing house couple", fallback: "real estate showing interior" },
  { slot: 39, query: "suburban neighborhood aerial view houses", fallback: "suburban houses neighborhood" },
  { slot: 40, query: "economic growth decline graph recession", fallback: "declining chart graph economy" },
  { slot: 41, query: "supply demand concept economics scale", fallback: "economics concept balance" },
  { slot: 42, query: "GDP growth chart economy data visualization", fallback: "economic growth chart" },
  { slot: 43, query: "investment portfolio screen monitor finance", fallback: "investment portfolio display" },
  { slot: 44, query: "financial advisor laptop office professional", fallback: "financial advisor office" },
  { slot: 45, query: "economy gears mechanism concept industrial", fallback: "mechanical gears industrial" },
  { slot: 46, query: "recession indicator chart graph economy", fallback: "recession economic chart" },
  { slot: 47, query: "business investment office meeting professional", fallback: "business meeting professional" },
  { slot: 48, query: "startup funding pitch presentation", fallback: "business pitch presentation" },
  { slot: 49, query: "debt balance scale finance concept", fallback: "justice scale finance" },
  { slot: 50, query: "world economy globe finance global", fallback: "world globe finance" },
  { slot: 51, query: "trillion dollar concept money stack", fallback: "large money stack currency" },
  { slot: 52, query: "global GDP comparison chart countries", fallback: "world economy comparison" },
  { slot: 53, query: "bank assets balance sheet financial statement", fallback: "financial report balance sheet" },
  { slot: 54, query: "financial statements closeup documents macro", fallback: "financial documents closeup" },
  { slot: 55, query: "wall street new york stock exchange", fallback: "wall street nyc finance" },
  { slot: 56, query: "stock exchange trading floor active", fallback: "stock trading floor" },
  { slot: 57, query: "personal finance budget planning couple", fallback: "personal finance household" },
  { slot: 58, query: "financial planning couple home desk", fallback: "financial planning home" },
  { slot: 59, query: "money future investment growth concept", fallback: "future investment growth" },
];
