// AUTO-GENERATED by scripts/google-tts-poc.ts — do not edit by hand
export const POC_DURATION_IN_FRAMES = 838;
export const POC_SENTENCES: Array<{
  text: string;
  startSeconds: number;
  endSeconds: number;
  words: Array<{ word: string; startSeconds: number; endSeconds: number }>;
}> = [
  {
    "text": "Is this the future of work?",
    "words": [
      {
        "word": "Is",
        "startSeconds": 0.1,
        "endSeconds": 0.5
      },
      {
        "word": "this",
        "startSeconds": 0.5,
        "endSeconds": 0.6
      },
      {
        "word": "the",
        "startSeconds": 0.6,
        "endSeconds": 0.9
      },
      {
        "word": "future",
        "startSeconds": 0.9,
        "endSeconds": 1.1
      },
      {
        "word": "of",
        "startSeconds": 1.1,
        "endSeconds": 1.2
      },
      {
        "word": "work?",
        "startSeconds": 1.2,
        "endSeconds": 1.5
      }
    ],
    "startSeconds": 0.1,
    "endSeconds": 1.5
  },
  {
    "text": "Nobody knows — but the signs are everywhere.",
    "words": [
      {
        "word": "Nobody",
        "startSeconds": 1.5,
        "endSeconds": 2.4
      },
      {
        "word": "knows",
        "startSeconds": 2.4,
        "endSeconds": 2.6
      },
      {
        "word": "but",
        "startSeconds": 2.6,
        "endSeconds": 3.5
      },
      {
        "word": "the",
        "startSeconds": 3.5,
        "endSeconds": 3.7
      },
      {
        "word": "signs",
        "startSeconds": 3.7,
        "endSeconds": 4
      },
      {
        "word": "are",
        "startSeconds": 4,
        "endSeconds": 4.2
      },
      {
        "word": "everywhere.",
        "startSeconds": 4.2,
        "endSeconds": 4.5
      }
    ],
    "startSeconds": 1.5,
    "endSeconds": 4.5
  },
  {
    "text": "Three hours per day: that's how long the average worker sits in meetings.",
    "words": [
      {
        "word": "hours",
        "startSeconds": 5.5,
        "endSeconds": 5.7
      },
      {
        "word": "per",
        "startSeconds": 5.7,
        "endSeconds": 6.1
      },
      {
        "word": "day:",
        "startSeconds": 6.1,
        "endSeconds": 6.2
      },
      {
        "word": "that's",
        "startSeconds": 6.2,
        "endSeconds": 7
      },
      {
        "word": "how",
        "startSeconds": 7,
        "endSeconds": 7.1
      },
      {
        "word": "long",
        "startSeconds": 7.1,
        "endSeconds": 7.3
      },
      {
        "word": "the",
        "startSeconds": 7.3,
        "endSeconds": 7.5
      },
      {
        "word": "average",
        "startSeconds": 7.5,
        "endSeconds": 7.8
      },
      {
        "word": "worker",
        "startSeconds": 7.8,
        "endSeconds": 8.2
      },
      {
        "word": "sits",
        "startSeconds": 8.2,
        "endSeconds": 8.4
      },
      {
        "word": "in",
        "startSeconds": 8.4,
        "endSeconds": 8.6
      },
      {
        "word": "meetings.",
        "startSeconds": 8.6,
        "endSeconds": 8.8
      }
    ],
    "startSeconds": 5.5,
    "endSeconds": 8.8
  },
  {
    "text": "Most could have been an email, a Slack message, or nothing at all!",
    "words": [
      {
        "word": "Most",
        "startSeconds": 8.8,
        "endSeconds": 9.8
      },
      {
        "word": "could",
        "startSeconds": 9.8,
        "endSeconds": 10.2
      },
      {
        "word": "have",
        "startSeconds": 10.2,
        "endSeconds": 10.2
      },
      {
        "word": "been",
        "startSeconds": 10.2,
        "endSeconds": 10.3
      },
      {
        "word": "an",
        "startSeconds": 10.3,
        "endSeconds": 10.5
      },
      {
        "word": "email,",
        "startSeconds": 10.5,
        "endSeconds": 10.6
      },
      {
        "word": "a",
        "startSeconds": 10.6,
        "endSeconds": 11.4
      },
      {
        "word": "Slack",
        "startSeconds": 11.4,
        "endSeconds": 11.5
      },
      {
        "word": "message,",
        "startSeconds": 11.5,
        "endSeconds": 11.8
      },
      {
        "word": "or",
        "startSeconds": 11.8,
        "endSeconds": 12.4
      },
      {
        "word": "nothing",
        "startSeconds": 12.4,
        "endSeconds": 12.6
      },
      {
        "word": "at",
        "startSeconds": 12.6,
        "endSeconds": 12.9
      },
      {
        "word": "all!",
        "startSeconds": 12.9,
        "endSeconds": 13
      }
    ],
    "startSeconds": 8.8,
    "endSeconds": 13
  },
  {
    "text": "Productivity, engagement, retention...",
    "words": [
      {
        "word": "Productivity,",
        "startSeconds": 13,
        "endSeconds": 14.2
      },
      {
        "word": "engagement,",
        "startSeconds": 14.2,
        "endSeconds": 15.3
      },
      {
        "word": "retention...",
        "startSeconds": 15.3,
        "endSeconds": 16.1
      }
    ],
    "startSeconds": 13,
    "endSeconds": 16.1
  },
  {
    "text": "all quietly eroding.",
    "words": [
      {
        "word": "all",
        "startSeconds": 16.1,
        "endSeconds": 17.1
      },
      {
        "word": "quietly",
        "startSeconds": 17.1,
        "endSeconds": 17.5
      },
      {
        "word": "eroding.",
        "startSeconds": 17.5,
        "endSeconds": 18
      }
    ],
    "startSeconds": 16.1,
    "endSeconds": 18
  },
  {
    "text": "Yet companies keep scheduling them; because busyness signals effort.",
    "words": [
      {
        "word": "Yet",
        "startSeconds": 18,
        "endSeconds": 18.9
      },
      {
        "word": "companies",
        "startSeconds": 18.9,
        "endSeconds": 19.5
      },
      {
        "word": "keep",
        "startSeconds": 19.5,
        "endSeconds": 19.8
      },
      {
        "word": "scheduling",
        "startSeconds": 19.8,
        "endSeconds": 20.2
      },
      {
        "word": "them;",
        "startSeconds": 20.2,
        "endSeconds": 20.5
      },
      {
        "word": "because",
        "startSeconds": 20.5,
        "endSeconds": 21.2
      },
      {
        "word": "busyness",
        "startSeconds": 21.2,
        "endSeconds": 21.7
      },
      {
        "word": "signals",
        "startSeconds": 21.7,
        "endSeconds": 22.2
      },
      {
        "word": "effort.",
        "startSeconds": 22.2,
        "endSeconds": 22.5
      }
    ],
    "startSeconds": 18,
    "endSeconds": 22.5
  },
  {
    "text": "The result is a workforce that feels exhausted — but accomplishes very little.",
    "words": [
      {
        "word": "The",
        "startSeconds": 22.5,
        "endSeconds": 23.4
      },
      {
        "word": "result",
        "startSeconds": 23.4,
        "endSeconds": 23.8
      },
      {
        "word": "is",
        "startSeconds": 23.8,
        "endSeconds": 24
      },
      {
        "word": "a",
        "startSeconds": 24,
        "endSeconds": 24.1
      },
      {
        "word": "workforce",
        "startSeconds": 24.1,
        "endSeconds": 24.6
      },
      {
        "word": "that",
        "startSeconds": 24.6,
        "endSeconds": 24.8
      },
      {
        "word": "feels",
        "startSeconds": 24.8,
        "endSeconds": 25.1
      },
      {
        "word": "exhausted",
        "startSeconds": 25.1,
        "endSeconds": 25.8
      },
      {
        "word": "but",
        "startSeconds": 25.8,
        "endSeconds": 26.4
      },
      {
        "word": "accomplishes",
        "startSeconds": 26.4,
        "endSeconds": 27
      },
      {
        "word": "very",
        "startSeconds": 27,
        "endSeconds": 27.3
      },
      {
        "word": "little.",
        "startSeconds": 27.3,
        "endSeconds": 27.4
      }
    ],
    "startSeconds": 22.5,
    "endSeconds": 27.4
  }
];
